package com.trainschedule

class ServiceConstants {
	
	public static final Map STATION_NAMES = [
		'Alewife Station':'Alewife',
		'Davis Station':'Davis',
		'Porter Square Station':'Porter Square',
		'Harvard Square Station':'Harvard Square',
		'Central Square Station':'Central Square',
		'Kendall/MIT Station':'Kendall/MIT',
		'Charles/MGH Station':'Charles/MGH',
		'Park St. Station':'Park Street',		
		'South Station':'South Station',
		'Broadway Station':'Broadway',
		'Andrew Station':'Andrew',
		'JFK/UMass Station':'JFK/UMass',
		'Savin Hill Station':'Savin Hill',
		'Fields Corner Station':'Fields Corner',
		'Shawmut Station':'Shawmut',
		'Ashmont Station':'Ashmont',
		'North Quincy Station':'North Quincy',
		'Wollaston Station':'Wollaston',
		'Quincy Center Station':'Quincy Center',
		'Quincy Adams Station':'Quincy Adams',
		'Braintree Station':'Braintree',
		'Oak Grove Station':'Oak Grove',
		'Malden Center Station':'Malden Center',
		'Wellington Station':'Wellington',
		'Sullivan Station':'Sullivan',
		'Community College Station':'Community College',
		'North Station':'North Station',
		'Haymarket Station':'Haymarket',		
		'Downtown Crossing Station':'Downtown Crossing',
		'Chinatown Station':'Chinatown',
		'Tufts Medical Center Station':'Tufts Medical',
		'Back Bay Station':'Back Bay',
		'Massachusetts Ave. Station':'Mass Ave',
		'Ruggles Station':'Ruggles',
		'Roxbury Crossing Station':'Roxbury Crossing',
		'Jackson Square Station':'Jackson Square',
		'Stony Brook Station':'Stony Brook',
		'Green St. Station':'Green Street',
		'Forest Hills Station':'Forest Hills',
		'Wonderland Station':'Wonderland',
		'Revere Beach Station':'Revere Beach',
		'Beachmont Station':'Beachmont',
		'Suffolk Downs Station':'Suffolk Downs',
		'Orient Heights Station':'Orient Heights',
		'Wood Island Station':'Wood Island',
		'Airport Station':'Airport',
		'Maverick Station':'Maverick',
		'Aquarium Station':'Aquarium',
		'State St. Station':'State Street',
		'Government Center Station':'Government Center',
		'Bowdoin Station':'Bowdoin'
		]

}
